apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: java-exchange-rate-import
  description: Points to my Java app catalog-info
spec:
  targets:
    - https://github.com/Ovvio2311/java-exchange-rate/blob/main/catalog-info.yaml
