name: Java CI
on: [push]
jobs:
  jenkins-container-pipeline:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jenkinsci/jenkinsfile-runner:latest
    steps:
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/checkout@v4
      - uses:
          jenkinsci/jfr-container-action@latest
        with:
          command: run
          jenkinsfile: Jenkinsfile
          pluginstxt: plugins.txt
          #jcasc: jcasc.yml
