name: Java CI
on: [push]
jobs:
  jenkins-container-pipeline:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jenkinsci/jenkinsfile-runner:latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Install additional tools
        run: apt-get update && apt-get install -y default-jdk
      - uses: jenkinsci/jfr-setup-action@master
      # - name: Build Jenkins WAR file
      #   run: |
      #     jar -cvf /app/jenkins/jenkins.war /app/jenkins/*
      #     mkdir -p /jenkins_new_plugins
      #     mkdir -p /jenkinsHome
      #     mkdir /app/jenkins/WEB-INF/groovy.init.d
      #     cp ${{ github.workspace }}/init.groovy /app/jenkins/WEB-INF/groovy.init.d/
      - uses:
          jenkinsci/jfr-container-action@master     
        with:
          command: run
          jenkinsfile: Jenkinsfile
          pluginstxt: plugins.txt
          jcasc: jcasc.yml
      - name: Ensure credentials are accessible
        run: |
          echo "Setting up credentials..."
          echo "${{ secrets.JENKINS_ADMIN_PASSWORD }}" > /tmp/jenkins_admin_password
          # Add additional commands to handle other credentials
